### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by twsouthwick** [ngocvantran/7Pass-Remake#3]
I don't see any license for the product.  Could you add one?  Since no work has been done over a year, I'd like to fork and publish it/maintain it.  Without a license, I don't know if I'm okay to publish changes to the code.  Thanks!

**Comment by corsairmarks** [comment]
I did a little digging.  The official website says it is GPL 2 because it contains code from actual KeePass, which is also GPL 2.  https://7pass.wordpress.com/about/license/

@twsouthwick do you want to collaborate on improving this in a fork?  I just took the Windows Phone plunge and I need access to my KeePass passwords.  I'm a professional C# developer but no experience with Win Phone yet.

**Comment by twsouthwick** [comment]
@corsairmarks This is somewhat old, but I've started a remake of this at https://github.com/twsouthwick/KeePassWin. Instead of building on this, I've rewritten it for UWP based on the latest KeePass. If you're still interested, I'd love some collaboration!

**Comment by corsairmarks** [comment]
@twsouthwick I would like to help.  I've been teaching myself UWP with a MS Band theming-app (not quite released yet but close).

**Comment by twsouthwick** [comment]
Very cool - let's continue the discussion on the repo I listed. I'm going to put up a roadmap soon (as well as a link to install the app), but feel free to open issues and start discussions there!
